name: Unsupported Device
description: Let's have a look if we can support your device
title: "Add support for ..."
labels: [new-device]
body:

  - type: markdown
    attributes:
      value: |
        ## Device

  - type: textarea
    id: unsupported_device_log
    attributes:
      label: Home Assistant log
      description: Enable [debug logging](https://github.com/vlebourl/custom_vesync#enable-debug-logging) and paste your full log here.
      value: |
        <details><summary>Logs</summary>

        ```
        Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Found the following devices:".
        ```

        </details>

  - type: markdown
    attributes:
      value: |
        ## Details

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: If you have any additional information for us, use the field below. Please note, you can attach screenshots or screen recordings here, by dragging and dropping files in the field below.

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
